#
# في هذا الملف ستجد كل المتغيرات التي تتحكم في إعدادات المدونة، شخصّها على حسب متطلباتك
#

# اسم المدونة الذي سيظهر في الأعلى
name: BMDZ

# وصف قصير للمدونة والذي سيظهر تحت اسمها وكجزء من عنوان المدونة في محركات البحث
description: رياضيات الباك

# رابط صورة المدونة
# لإستخدام صورة هويتك في GitHub ضع 
# ولإخفاء الصورة نهائيًا احذف الرابط من المتغير
avatar: Bac-math-dz.png


#
# المتغيرات الآتية هي خيارية، عدل عليها إذا أردت تخصيص أكثر للمدونة
#

# لكل هوية تضعها هنا ستظهر أيقونة في أسفل المدونة
footer-links:
  dribbble:
  email: bachirmath1@gmail.com
  facebook: profile.php?id=61556163150058
  flickr:
  github: #bachirmath
  instagram:
  linkedin:
  pinterest:
  rss:
  twitter: 
  stackoverflow: # هويتك في stackoverflow مثلا: "users/50476/bart-kiers"
  googleplus: # رقم التعريف عندما تزور هويتك (كل ما يتبع plus.google.com/)
  youtube: channel/UCJWV4mEq_5jfxLTUxAbsIyg
    

  

# ضع الاسم Disqus القصير الخاص بك (الاسم القصير وليس اسم المستخدم) لتفعيل الردود على المدونة
# ستجد الاسم القصير الخاص بك في إعدادات حسابك في Disqus
disqus:

# إذا أردت تفعيل إحصاءات الزوار في Google Analytics أدخل المعرف الخاص بك (مثلاً UA-2110908-2)
google_analytics:

# عنوان موقعك مثلاً http://barryclark.github.io
# يستخدم هذا المتغير في الـRSS والـSitemap.xml
url: https://bmdz1.github.io

# إذا كانت المدونة خاصة للصفحات المشاريع في GitHub (http://yourusername.github.io/repository-name مثلاً) عدل هذا المتغير ليطابق اسم المشروع
baseurl: ""


#
# هذه المتغيرات خاصة بـJekyll ولا أنصح بتعديلها، لذلك لا حاجة لشرحها
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: "highlight"

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
   
# Set the Sass partials directory, as we're using @imports

sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
#gems:
 # - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
 # - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  #- jekyll-scholar

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
